### ISSUE TITLE
Admin Settings Interface

### ISSUE THREAD

**Issue by ArchBlood** [cuzy-app/humhub-modules-auth-keycloak#2]
You should use the settings page for entering the required information instead of going through the `common.php` file.

**Comment by ArchBlood** [comment]
Of course, you can add more settings to this page in regards to other options provided by the authclient, but seeing as I do not know what they are supposed to do I go with the basic options needed to make the client function, hope you enjoy @funkycram

**Comment by funkycram** [comment]
Yes, when this module is at the version 1.0 the settings will be available with GUI. But for the moment my clients do not need it, so I did not develop it. If you enjoy the module and want to contribute, feel free submitting a PR.

**Comment by ArchBlood** [comment]
> Yes, when this module is at the version 1.0 the settings will be available with GUI. But for the moment my clients do not need it, so I did not develop it. If you enjoy the module and want to contribute, feel free submitting a PR.

Done with #1

**Comment by funkycram** [comment]
Many thanks @ArchBlood ! This is a great improvement!
I have added a commit: https://github.com/cuzy-app/humhub-modules-auth-keycloak/commit/a3c65d2cca8719455e8b8c9ce36ab5fa75997ad9

Important: as I have transferred all settings in the ConfigureForm, you need to save settings again in order to have the module working (as you have already enabled it because of your intermediate version).

I did not take time to make many tests, I will do next week, don't hesitate if you find bugs. Thanks for your contribution!

**Comment by ArchBlood** [comment]
> Many thanks @ArchBlood ! This is a great improvement!
> I have added a commit: [a3c65d2](https://github.com/cuzy-app/humhub-modules-auth-keycloak/commit/a3c65d2cca8719455e8b8c9ce36ab5fa75997ad9)
> 
> Important: as I have transferred all settings in the ConfigureForm, you need to save settings again in order to have the module working (as you have already enabled it because of your intermediate version).
> 
> I did not take time to make many tests, I will do next week, don't hesitate if you find bugs. Thanks for your contribution!

From looking at it, I'm seeing a few required fields in the optional settings? I don't think this should be done as it would defeat the purpose of them being optional, either the optional tag should be dropped or the requirement should, your thoughts?

**Comment by funkycram** [comment]
Yes, you are right, I just changed it, thank you.
